package com.hololive.cardgame.service;

import java.util.List;
import java.util.Map;

public record AttackRestAndPayloadContext(
    Long attackerCardInstanceId,
    String attackerCardId,
    String attackerZone,
    Long targetCardInstanceId,
    boolean passiveGiftTargetRestrictionToCollab,
    boolean passiveGiftTargetRestrictionApplied,
    boolean damageRedirectApplied,
    String targetMainColor,
    String artName,
    Object artOrderIndex,
    Map<String, Integer> artBaseCost,
    Map<String, Integer> artCost,
    Map<String, Object> passiveGiftArtCostReduction,
    Map<String, Object> costPayment,
    Map<String, Object> damagePayloadFields,
    Map<String, Object> holoxReveal,
    Map<String, Object> hbp02039SupportRecovery,
    Map<String, Object> hbp02040LifeLoss,
    Map<String, Object> defenderDamageReceivedGift,
    int artTotalDamage,
    Map<String, Object> artSummary,
    Map<String, Object> officialCardArtExtraSummary,
    Map<String, Object> officialOshiArtReactiveSummary,
    Map<String, Object> officialOshiSelfDownedSummary,
    Map<String, Object> artDownTriggeredEffects,
    Map<String, Object> postTriggerEffects,
    Map<String, Object> defenderGiftEffects,
    boolean hasNextPerformanceAction,
    Long lostLifeCardInstanceId,
    AttackPendingDecision postTriggerConfirmDecision,
    AttackPendingDecision defenderGiftConfirmDecision,
    List<Map<String, Object>> additionalEffectSummaries
) {
    public static AttackRestAndPayloadContext attackArt(
        Long attackerCardInstanceId,
        String attackerCardId,
        String attackerZone,
        Long targetCardInstanceId,
        boolean passiveGiftTargetRestrictionToCollab,
        boolean passiveGiftTargetRestrictionApplied,
        boolean damageRedirectApplied,
        String targetMainColor,
        String artName,
        Object artOrderIndex,
        Map<String, Integer> artBaseCost,
        Map<String, Integer> artCost,
        Map<String, Object> passiveGiftArtCostReduction,
        Map<String, Object> costPayment,
        Map<String, Object> damagePayloadFields,
        Map<String, Object> holoxReveal,
        Map<String, Object> hbp02039SupportRecovery,
        Map<String, Object> hbp02040LifeLoss,
        Map<String, Object> defenderDamageReceivedGift,
        int artTotalDamage,
        Map<String, Object> artSummary,
        Map<String, Object> officialCardArtExtraSummary,
        Map<String, Object> officialOshiArtReactiveSummary,
        Map<String, Object> officialOshiSelfDownedSummary,
        Map<String, Object> artDownTriggeredEffects,
        Map<String, Object> postTriggerEffects,
        Map<String, Object> defenderGiftEffects,
        boolean hasNextPerformanceAction,
        Long lostLifeCardInstanceId,
        AttackPendingDecision postTriggerConfirmDecision,
        AttackPendingDecision defenderGiftConfirmDecision,
        List<Map<String, Object>> additionalEffectSummaries
    ) {
        return new AttackRestAndPayloadContext(
            attackerCardInstanceId,
            attackerCardId,
            attackerZone,
            targetCardInstanceId,
            passiveGiftTargetRestrictionToCollab,
            passiveGiftTargetRestrictionApplied,
            damageRedirectApplied,
            targetMainColor,
            artName,
            artOrderIndex,
            artBaseCost,
            artCost,
            passiveGiftArtCostReduction,
            costPayment,
            damagePayloadFields,
            holoxReveal,
            hbp02039SupportRecovery,
            hbp02040LifeLoss,
            defenderDamageReceivedGift,
            artTotalDamage,
            artSummary,
            officialCardArtExtraSummary,
            officialOshiArtReactiveSummary,
            officialOshiSelfDownedSummary,
            artDownTriggeredEffects,
            postTriggerEffects,
            defenderGiftEffects,
            hasNextPerformanceAction,
            lostLifeCardInstanceId,
            postTriggerConfirmDecision,
            defenderGiftConfirmDecision,
            additionalEffectSummaries
        );
    }
}
