-- 匯入官方卡表批次資料（來源：HSD12）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD12&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP04-050', 'シオリ・ノヴェラ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hBP04-050_02_C.png', 'MEMBER', 'HSD12', 'HBP04-050', '["#EN", "#Advent"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1766&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP04-050', 110, 'DEBUT', 'BLUE', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP04-050';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP04-050', 'しおり～ん！ 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇しおり～ん！ 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP04-063', '古石ビジュー', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hBP04-063_02_C.png', 'MEMBER', 'HSD12', 'HBP04-063', '["#EN", "#Advent", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1767&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP04-063', 110, 'DEBUT', 'PURPLE', NULL, 0, '{"キーワード": "ギフトキラキラ コセキ！ \n相手のターンで、このホロメンがダウンした時、自分のデッキを1枚引く。", "エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP04-063';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP04-063', 'ボンビジュー！ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇ボンビジュー！ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-001', 'シオリ・ノヴェラ', 'OSR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-001_OSR.png', 'OSHI', 'HSD12', 'HSD12-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1750&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD12-001', 5, 'BLUE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD12-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD12-001', 'NORMAL', '収集家', '[ターンに1回]自分のデッキの上から3枚を見る。その中から、サポートカード1枚を公開し、手札に加える。そして残ったカードを好きな順でデッキの下に戻す。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]自分のデッキの上から3枚を見る。その中から、サポートカード1枚を公開し、手札に加える。そして残ったカードを好きな順でデッキの下に戻す。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD12-001', 'SP', 'リベリオン', '[ゲームに1回]相手のDebut以外のバックホロメン1人に、自分のアーカイブのサポートカード1枚につき、特殊ダメージ10を与える。', 3, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]相手のDebut以外のバックホロメン1人に、自分のアーカイブのサポートカード1枚につき、特殊ダメージ10を与える。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-002', '古石ビジュー', 'OSR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-002_OSR.png', 'OSHI', 'HSD12', 'HSD12-002', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1751&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD12-002', 5, 'PURPLE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD12-002';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD12-002', 'NORMAL', 'Biboo Tax', '[ターンに1回]お互いのエールデッキの上から1枚をアーカイブする。アーカイブしたエール1色につき、自分のデッキを1枚引く。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]お互いのエールデッキの上から1枚をアーカイブする。アーカイブしたエール1色につき、自分のデッキを1枚引く。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD12-002', 'SP', '古代魔石の輝き', '[ゲームに1回]相手のセンターホロメンに、自分のアーカイブの[#Adventを持つホロメンとエール]1枚につき、特殊ダメージ10を与える。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]相手のセンターホロメンに、自分のアーカイブの[#Adventを持つホロメンとエール]1枚につき、特殊ダメージ10を与える。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-003', 'シオリ・ノヴェラ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-003_C.png', 'MEMBER', 'HSD12', 'HSD12-003', '["#EN", "#Advent"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1752&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-003', 130, 'DEBUT', 'BLUE', NULL, 0, '{"キーワード": "コラボエフェクトパレ・モンローズのお話をお聞きになったことは？ \n相手のバックホロメン1人に特殊ダメージ10を与える。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-003', 'アデュー、親愛なる聞き手様 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇アデュー、親愛なる聞き手様 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-004', 'シオリ・ノヴェラ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-004_C.png', 'MEMBER', 'HSD12', 'HSD12-004', '["#EN", "#Advent"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1753&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-004', 170, 'FIRST', 'BLUE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-004', '不穏な忠告 20', 'このアーツは、相手のバックホロメンも対象にできる。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇不穏な忠告 20", "rawEffect": "このアーツは、相手のバックホロメンも対象にできる。"}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-004', 'Just a Humble, Kind Witch 30', '自分のアーカイブにサポートカードが4枚以上あるなら、自分のエールデッキの上から1枚を自分の#Adventを持つホロメンに送る。', '{"BLUE": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "青Just a Humble, Kind Witch 30", "rawEffect": "自分のアーカイブにサポートカードが4枚以上あるなら、自分のエールデッキの上から1枚を自分の#Adventを持つホロメンに送る。"}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-005', 'シオリ・ノヴェラ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-005_U.png', 'MEMBER', 'HSD12', 'HSD12-005', '["#EN", "#Advent"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1754&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-005', 160, 'FIRST', 'BLUE', NULL, 1, '{"キーワード": "コラボエフェクト『異世界への旅立ちと幸せ』 \n自分のアーカイブのエール1枚を自分の#Adventを持つホロメンに送る。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-005', '車窓から見える星がとてもきれいよ 40', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇車窓から見える星がとてもきれいよ 40", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-007', 'シオリ・ノヴェラ', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-007_RR.png', 'MEMBER', 'HSD12', 'HSD12-007', '["#EN", "#Advent"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1756&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-007', 200, 'SECOND', 'BLUE', NULL, 2, '{"キーワード": "ギフトどんな知識が得られるかしら \n[ターンに1回]このホロメンが相手のホロメンをダウンさせた時、自分のアーカイブのLIMITED以外のサポートカード1枚を手札に戻す。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-007', '私達を見くびらないで貰える？ 110白+50', '相手のDebut以外のホロメン1人に、自分のステージの#Adventを持つホロメン1人につき、特殊ダメージ10を与える。', '{"BLUE": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "青◇◇私達を見くびらないで貰える？ 110白+50", "rawEffect": "相手のDebut以外のホロメン1人に、自分のステージの#Adventを持つホロメン1人につき、特殊ダメージ10を与える。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-008', '古石ビジュー', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-008_C.png', 'MEMBER', 'HSD12', 'HSD12-008', '["#EN", "#Advent", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1757&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-008', 110, 'DEBUT', 'PURPLE', NULL, 0, '{"キーワード": "コラボエフェクト花売りの少女 \n自分が後攻で最初のターンなら、お互いのステージのエール1枚につき、自分のデッキを1枚引く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-008';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-008', '私……この頃よく夢を見るの。 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇私……この頃よく夢を見るの。 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-009', '古石ビジュー', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-009_C.png', 'MEMBER', 'HSD12', 'HSD12-009', '["#EN", "#Advent", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1758&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-009', 130, 'FIRST', 'PURPLE', NULL, 1, '{"キーワード": "ブルームエフェクト賑やかな家族 \n自分のデッキの上から3枚を見る。その中から、#Adventを持つホロメン1枚を公開し、手札に加える。そして残ったカードを好きな順でデッキの下に戻す。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-009', 'とっても感謝してるの 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇とっても感謝してるの 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-010', '古石ビジュー', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-010_U.png', 'MEMBER', 'HSD12', 'HSD12-010', '["#EN", "#Advent", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1759&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-010', 170, 'FIRST', 'PURPLE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-010';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-010', '滲んでいく輝き 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇滲んでいく輝き 30", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-010', 'Your Princess AWAKENS! 50', 'このホロメンの紫以外のエール1枚をアーカイブできる：自分のアーカイブのホロメン1枚を手札に戻す。', '{"PURPLE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇Your Princess AWAKENS! 50", "rawEffect": "このホロメンの紫以外のエール1枚をアーカイブできる：自分のアーカイブのホロメン1枚を手札に戻す。"}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-011', '古石ビジュー', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-011_RR.png', 'MEMBER', 'HSD12', 'HSD12-011', '["#EN", "#Advent", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1760&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-011', 200, 'SECOND', 'PURPLE', NULL, 2, '{"キーワード": "ブルームエフェクトビブーと遊んでいかない？ \n自分のデッキを1枚引く。その後、自分のステージのエール1枚をアーカイブできる。アーカイブしたなら、自分のステージのホロメン1人を選ぶ。このターンの間、選んだホロメンのアーツ+40。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-011';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-011', 'キラキラぜーんぶ受け止めて！ 110黄+50', 'お互いのアーカイブのエール1色につき、このアーツに必要な無色-1。', '{"PURPLE": 1, "COLORLESS": 3}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇◇◇キラキラぜーんぶ受け止めて！ 110黄+50", "rawEffect": "お互いのアーカイブのエール1色につき、このアーツに必要な無色-1。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-012', 'ネリッサ・レイヴンクロフト', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-012_C.png', 'MEMBER', 'HSD12', 'HSD12-012', '["#EN", "#Advent", "#歌", "#トリ"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1761&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-012', 140, 'DEBUT', 'PURPLE', NULL, 0, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-012';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-012', '綾なす想いは、儚きブルー 80', '自分のライフが3以下なら、このアーツに必要な無色-2。', '{"PURPLE": 1, "COLORLESS": 3}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇◇◇綾なす想いは、儚きブルー 80", "rawEffect": "自分のライフが3以下なら、このアーツに必要な無色-2。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD12-013', 'モココ・アビスガード', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD12/hSD12-013_C.png', 'MEMBER', 'HSD12', 'HSD12-013', '["#EN", "#Advent", "#ケモミミ"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1762&expansion=hSD12&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD12-013', 130, 'DEBUT', 'RED', NULL, 0, '{"キーワード": "コラボエフェクトハッピー☆パピー -MOCOCO- \n自分のステージのホロメン全員が#Adventを持つホロメンなら、自分のバックポジションのDebutホロメン1人をデッキの下に戻せる：自分のデッキを2枚引く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD12-013';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD12-013', 'ほんまにほんま～！！ 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇ほんまにほんま～！！ 30", "rawEffect": ""}'::jsonb, 0);

COMMIT;
