-- 匯入官方卡表批次資料（來源：HSD11）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD11&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-001', '虎金妃笑虎', 'OSR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-001_OSR.png', 'OSHI', 'HSD11', 'HSD11-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1469&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD11-001', 5, 'YELLOW', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD11-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD11-001', 'NORMAL', '虎視眈々', '[ターンに1回]自分のアーカイブのエール1～2枚を自分のエールが付いていない#FLOW GLOWを持つホロメン1人に送る。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]自分のアーカイブのエール1～2枚を自分のエールが付いていない#FLOW GLOWを持つホロメン1人に送る。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD11-001', 'SP', 'ニコたんの名を呼ぶがいいさ！', '[ゲームに1回]自分の#FLOW GLOWを持つホロメンの能力でエールをアーカイブした時に使える：相手のセンターホロメンかコラボホロメンどちらかに、アーカイブしたエール1枚につき、特殊ダメージ30を与える。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]自分の#FLOW GLOWを持つホロメンの能力でエールをアーカイブした時に使える：相手のセンターホロメンかコラボホロメンどちらかに、アーカイブしたエール1枚につき、特殊ダメージ30を与える。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-002', '虎金妃笑虎', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-002_C.png', 'MEMBER', 'HSD11', 'HSD11-002', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1470&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-002', 130, 'DEBUT', 'YELLOW', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-002';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-002', 'ニコたんが～来たァー！ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇ニコたんが～来たァー！ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-003', '虎金妃笑虎', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-003_C_re.png', 'MEMBER', 'HSD11', 'HSD11-003', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1471&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-003', 180, 'FIRST', 'YELLOW', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-003', 'にこと出会えたの何かのキセキ 50', '', '{"COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇にこと出会えたの何かのキセキ 50", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-003', '期待せよ 牙で噛まれちゃうシゲキ 80', '', '{"COLORLESS": 3}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇◇期待せよ 牙で噛まれちゃうシゲキ 80", "rawEffect": ""}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-004', '虎金妃笑虎', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-004_U_re.png', 'MEMBER', 'HSD11', 'HSD11-004', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1472&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-004', 150, 'FIRST', 'YELLOW', NULL, 1, '{"キーワード": "ブルームエフェクト人を笑顔にするためならば \n自分のステージのエール2枚をアーカイブできる：自分のアーカイブの〈虎金妃笑虎〉1枚を手札に戻す。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-004', '自分の人生すらも捧げられる 30', '自分のエールデッキの上から1枚を自分の〈虎金妃笑虎〉に送れる。', '{"YELLOW": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄◇自分の人生すらも捧げられる 30", "rawEffect": "自分のエールデッキの上から1枚を自分の〈虎金妃笑虎〉に送れる。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-005', '虎金妃笑虎', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-005_U.png', 'MEMBER', 'HSD11', 'HSD11-005', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1473&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-005', 160, 'FIRST', 'YELLOW', NULL, 1, '{"キーワード": "コラボエフェクトFLOW GLOWのお笑い担当 \n自分のアーカイブのエール1枚を自分の#FLOW GLOWを持つバックホロメンに送れる。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-005', '百折不撓 30+', '自分のステージにエールが5枚以上あるなら、このアーツ+20。', '{"YELLOW": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄百折不撓 30+", "rawEffect": "自分のステージにエールが5枚以上あるなら、このアーツ+20。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-006', '虎金妃笑虎', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-006_RR.png', 'MEMBER', 'HSD11', 'HSD11-006', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1474&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-006', 210, 'SECOND', 'YELLOW', NULL, 2, '{"キーワード": "ギフト戯笑の使者 \n自分のパフォーマンスステップが開始する時、自分の手札の#FLOW GLOWを持つホロメン1枚をアーカイブできる：自分のアーカイブの黄エール1枚を自分の〈虎金妃笑虎〉に送る。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-006';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-006', '虎嘯風生 40+赤+50', 'このホロメンのエールを好きな枚数アーカイブできる：アーカイブしたエール1枚につき、このアーツ+40。', '{"YELLOW": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄虎嘯風生 40+赤+50", "rawEffect": "このホロメンのエールを好きな枚数アーカイブできる：アーカイブしたエール1枚につき、このアーツ+40。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-007', '水宮枢', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-007_C.png', 'MEMBER', 'HSD11', 'HSD11-007', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1475&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-007', 120, 'DEBUT', 'BLUE', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-007', 'しゅぴしゅわー 20', '相手のセンターポジションのホロメン1人は、次の相手のターンが終了するまでバトンタッチに必要な無色+1。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇しゅぴしゅわー 20", "rawEffect": "相手のセンターポジションのホロメン1人は、次の相手のターンが終了するまでバトンタッチに必要な無色+1。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-008', '水宮枢', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-008_C.png', 'MEMBER', 'HSD11', 'HSD11-008', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1476&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-008', 160, 'FIRST', 'BLUE', NULL, 1, '{"キーワード": "コラボエフェクトFLOW GLOWのえらい宣伝担当 \n相手のセンターポジションのホロメン1人は、次の相手のターンが終了するまでバトンタッチに必要な無色+1。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-008';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-008', '愛は時間ですよ 30', 'このアーツの対象が相手のバトンタッチに必要な無色が2つ以上のホロメンなら、自分のエールデッキの上から1枚を自分のバックホロメンに送る。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇愛は時間ですよ 30", "rawEffect": "このアーツの対象が相手のバトンタッチに必要な無色が2つ以上のホロメンなら、自分のエールデッキの上から1枚を自分のバックホロメンに送る。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD11-009', '水宮枢', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD11/hSD11-009_RR.png', 'MEMBER', 'HSD11', 'HSD11-009', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1477&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD11-009', 210, 'SECOND', 'BLUE', NULL, 2, '{"キーワード": "コラボエフェクト感情の伝令者 \n相手のセンターポジションのホロメン1人は、次の相手のターンが終了するまでバトンタッチに必要な無色+3。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD11-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD11-009', 'スゥイートオブセッション 100紫+50', 'このアーツの対象のホロメンに、そのホロメンのバトンタッチに必要な無色1つにつき、特殊ダメージ10を与える。', '{"BLUE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "青◇スゥイートオブセッション 100紫+50", "rawEffect": "このアーツの対象のホロメンに、そのホロメンのバトンタッチに必要な無色1つにつき、特殊ダメージ10を与える。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD10-010', '響咲リオナ', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD10/hSD10-010_RR.png', 'MEMBER', 'HSD10', 'HSD10-010', '["#DEV_IS", "#FLOW"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1465&expansion=hSD11&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD10-010', 170, 'SPOT', 'COLORLESS', NULL, 0, '{"キーワード": "コラボエフェクト私の元においで～っ \n自分の手札1枚をアーカイブできる：自分のデッキから、[コラボエフェクトと#FLOW GLOWを持つホロメン]1枚を公開し、手札に加える。そしてデッキをシャッフルする。", "エクストラ": "このホロメンはBloomできない"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD10-010';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD10-010', 'RIONA IN DA HOUSE～! 50+', '自分のステージに#FLOW GLOWを持つ2nd以上のホロメンがいるなら、このアーツ+30。', '{"COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇RIONA IN DA HOUSE～! 50+", "rawEffect": "自分のステージに#FLOW GLOWを持つ2nd以上のホロメンがいるなら、このアーツ+30。"}'::jsonb, 0);

COMMIT;
