-- 匯入官方卡表批次資料（來源：HSD04）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD04&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-012', 'スバちょこルーナ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-012_U.png', 'SUPPORT', 'HSD04', 'HSD04-012', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=264&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-012', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-012_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=264&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-013', 'ちょこのオムライス', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-013_C.png', 'SUPPORT', 'HSD04', 'HSD04-013', '["#食べ物"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=265&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-013', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-013_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=265&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-014', 'しょこら', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-014_C.png', 'SUPPORT', 'HSD04', 'HSD04-014', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=266&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-014', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-014_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=266&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-104', 'ふつうのパソコン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-104_C.png', 'SUPPORT', 'HBP01', 'HBP01-104', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=145&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-104', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-104_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=145&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-106', 'あとは任せた！', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-106_U.png', 'SUPPORT', 'HBP01', 'HBP01-106', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=147&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-106', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-106_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=147&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-016', '春先のどか', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-016_C.png', 'SUPPORT', 'HSD01', 'HSD01-016', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=16&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-016', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-016_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=16&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-017', 'マネちゃん', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'SUPPORT', 'HSD01', 'HSD01-017', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-017', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-019', 'スゴイパソコン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-019_C_02.png', 'SUPPORT', 'HSD01', 'HSD01-019', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=19&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-019', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-019_C_02.png', 'https://hololive-official-cardgame.com/cardlist/?id=19&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-001', '癒月ちょこ', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-001_OC.png', 'OSHI', 'HSD04', 'HSD04-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=253&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-001_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=253&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD04-001', 5, 'PURPLE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD04-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD04-001', 'NORMAL', 'パープルマイク', '[ホロパワー：2消費][ターンに1回]このターンの間、自分の紫センターホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：2消費][ターンに1回]このターンの間、自分の紫センターホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD04-001', 'SP', 'カードチェンジ', '[ホロパワー：1消費][ゲームに1回]自分のデッキを2枚引いた後、手札1枚をアーカイブする。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：1消費][ゲームに1回]自分のデッキを2枚引いた後、手札1枚をアーカイブする。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-002', '癒月ちょこ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-002_C.png', 'MEMBER', 'HSD04', 'HSD04-002', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=254&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-002', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-002_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=254&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-002', 100, 'DEBUT', 'PURPLE', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-002';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-002', '魔界の保健医 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇魔界の保健医 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-003', '癒月ちょこ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-003_C.png', 'MEMBER', 'HSD04', 'HSD04-003', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=255&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-003', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-003_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=255&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-003', 60, 'DEBUT', 'PURPLE', NULL, 0, '{"キーワード": "コラボエフェクトグッイブニ～ング \n自分の推しホロメンの色が紫の時、自分のデッキを1枚引く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-003', 'マイキュ～トスチュ～デ～ンツ 30', '', '{"PURPLE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇マイキュ～トスチュ～デ～ンツ 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-004', '癒月ちょこ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-004_U.png', 'MEMBER', 'HSD04', 'HSD04-004', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=256&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-004', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-004_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=256&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-004', 60, 'DEBUT', 'PURPLE', NULL, 0, '{"キーワード": "コラボエフェクト地獄盛りごはん \n自分の手札1枚をアーカイブできる：自分のデッキから、#食べ物を持つイベント1枚を公開し、手札に加える。そしてデッキをシャッフルする。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-004', 'いっぱい食べてね♡ 20', '', '{"PURPLE": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫いっぱい食べてね♡ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-005', '癒月ちょこ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-005_C.png', 'MEMBER', 'HSD04', 'HSD04-005', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=257&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-005', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-005_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=257&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-005', 140, 'FIRST', 'PURPLE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-005', 'おつかれいと…… 20', '', '{"PURPLE": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫おつかれいと…… 20", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-005', 'あ～む（ﾁｭｯ） 40', '', '{"PURPLE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇あ～む（ﾁｭｯ） 40", "rawEffect": ""}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-006', '癒月ちょこ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-006_C.png', 'MEMBER', 'HSD04', 'HSD04-006', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=258&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-006', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-006_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=258&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-006', 130, 'FIRST', 'PURPLE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-006';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-006', '禁断のキッス 30', 'このアーツで相手のホロメンにダメージを与えた時、与えたダメージ10につき、このホロメンのHP10回復。', '{"PURPLE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇禁断のキッス 30", "rawEffect": "このアーツで相手のホロメンにダメージを与えた時、与えたダメージ10につき、このホロメンのHP10回復。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-007', '癒月ちょこ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-007_U.png', 'MEMBER', 'HSD04', 'HSD04-007', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=259&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-007', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-007_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=259&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-007', 110, 'FIRST', 'PURPLE', NULL, 1, '{"キーワード": "ブルームエフェクトちょっこーん！ \n自分のアーカイブのLIMITED以外のイベント1枚を手札に戻せる。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-007', '大好き！ちゅっ♡ 30', '自分のバックホロメン1人のHP20回復。', '{"COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇大好き！ちゅっ♡ 30", "rawEffect": "自分のバックホロメン1人のHP20回復。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-008', '癒月ちょこ', 'R', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-008_R.png', 'MEMBER', 'HSD04', 'HSD04-008', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=260&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-008', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-008_R.png', 'https://hololive-official-cardgame.com/cardlist/?id=260&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-008', 230, 'FIRST', 'PURPLE', NULL, 1, '{"エクストラ": "このホロメンがダウンした時、自分のライフ-2"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-008';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-008', 'がんばってつくったよ 40', '', '{"PURPLE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇がんばってつくったよ 40", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-008', '召し上がれ 60+', '自分のアーカイブの#食べ物を持つイベント1枚を手札に戻せる：このアーツ+20。', '{"PURPLE": 2, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫紫◇召し上がれ 60+", "rawEffect": "自分のアーカイブの#食べ物を持つイベント1枚を手札に戻せる：このアーツ+20。"}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-009', '癒月ちょこ', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-009_RR.png', 'MEMBER', 'HSD04', 'HSD04-009', '["#JP", "#2期生", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=261&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-009', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-009_RR.png', 'https://hololive-official-cardgame.com/cardlist/?id=261&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-009', 190, 'SECOND', 'PURPLE', NULL, 2, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-009', '33… 22… 11… 50緑+50', '', '{"PURPLE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇33… 22… 11… 50緑+50", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-009', 'あくとっ 60+緑+50', 'このターンに自分が使っていたイベント1枚につき、このアーツ+40。', '{"PURPLE": 2, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫紫◇あくとっ 60+緑+50", "rawEffect": "このターンに自分が使っていたイベント1枚につき、このアーツ+40。"}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-010', '大空スバル', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-010_U.png', 'MEMBER', 'HSD04', 'HSD04-010', '["#JP", "#2期生"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=262&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-010', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-010_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=262&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-010', 60, 'SPOT', 'COLORLESS', NULL, 0, '{"キーワード": "コラボエフェクトちよこーーッ！！ \n自分のセンターホロメンが〈癒月ちょこ〉の時、自分のアーカイブのエール1枚を自分のホロメンに送れる。", "エクストラ": "このホロメンはBloomできない"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-010';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-010', '地獄くじ引き、引かせるぞっ 20', '', '{"COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇地獄くじ引き、引かせるぞっ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD04-011', '姫森ルーナ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-011_U.png', 'MEMBER', 'HSD04', 'HSD04-011', '["#JP", "#4期生"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=263&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD04-011', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD04/hSD04-011_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=263&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD04-011', 60, 'SPOT', 'COLORLESS', NULL, 0, '{"キーワード": "コラボエフェクトちょこてんて～ \n自分のホロパワーを見る。その中から1枚を公開し、手札に加える。そして自分の手札1枚をホロパワーにする。", "エクストラ": "このホロメンはBloomできない"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD04-011';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD04-011', 'んな～～～～～～～～ 10', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇んな～～～～～～～～ 10", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY05-001', '紫エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY05-001_C.png', 'CHEER', 'HY05', 'HY05-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=267&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY05-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY05-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=267&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD04&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

COMMIT;
