-- 匯入官方卡表批次資料（來源：HSD05）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD05&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HPR-002', 'ReGLOSS', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hPR-002_U.png', 'SUPPORT', 'HPR', 'HPR-002', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=530&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HPR-002', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hPR-002_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=530&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-014', 'ばんぺん', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-014_C.png', 'SUPPORT', 'HSD05', 'HSD05-014', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=531&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-014', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-014_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=531&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-104', 'ふつうのパソコン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-104_C.png', 'SUPPORT', 'HBP01', 'HBP01-104', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=145&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-104', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-104_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=145&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-108', 'じゃあ敵だね', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-108_U.png', 'SUPPORT', 'HBP01', 'HBP01-108', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=149&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-108', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-108_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=149&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-016', '春先のどか', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-016_C.png', 'SUPPORT', 'HSD01', 'HSD01-016', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=16&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-016', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-016_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=16&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-017', 'マネちゃん', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'SUPPORT', 'HSD01', 'HSD01-017', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-017', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-001', '轟はじめ', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-001_OC.png', 'OSHI', 'HSD05', 'HSD05-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=517&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-001_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=517&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD05-001', 5, 'WHITE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD05-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD05-001', 'NORMAL', 'ホワイトマイク', '[ターンに1回]このターンの間、自分の白センターホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]このターンの間、自分の白センターホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD05-001', 'SP', 'クイックガード', '[ゲームに1回]相手のターンで、自分の白ホロメンが相手からダメージを受ける時に使える：そのホロメン1人が受けるダメージ-20。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]相手のターンで、自分の白ホロメンが相手からダメージを受ける時に使える：そのホロメン1人が受けるダメージ-20。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-002', '轟はじめ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-002_C.png', 'MEMBER', 'HSD05', 'HSD05-002', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=518&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-002', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-002_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=518&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-002', 100, 'DEBUT', 'WHITE', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-002';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-002', 'ぶんぶんぶーん！ 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇ぶんぶんぶーん！ 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-003', '轟はじめ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-003_C.png', 'MEMBER', 'HSD05', 'HSD05-003', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=519&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-003', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-003_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=519&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-003', 60, 'DEBUT', 'WHITE', NULL, 0, '{"キーワード": "コラボエフェクトこんちくわ \nこのターンの間、自分の#ReGLOSSを持つセンターホロメンのアーツ+10。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-003', 'お洒落番長 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇お洒落番長 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-004', '轟はじめ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-004_U.png', 'MEMBER', 'HSD05', 'HSD05-004', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=520&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-004', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-004_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=520&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-004', 120, 'DEBUT', 'WHITE', NULL, 0, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-004', 'ReGLOSSの番長 40', '', '{"WHITE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白◇ReGLOSSの番長 40", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-005', '轟はじめ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-005_C.png', 'MEMBER', 'HSD05', 'HSD05-005', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=521&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-005', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-005_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=521&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-005', 140, 'FIRST', 'WHITE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-005', '夜路紫駆！ 40', '', '{"WHITE": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白夜路紫駆！ 40", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-005', 'うぃー！ 60', '', '{"COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇うぃー！ 60", "rawEffect": ""}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-006', '轟はじめ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-006_C.png', 'MEMBER', 'HSD05', 'HSD05-006', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=522&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-006', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-006_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=522&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-006', 100, 'FIRST', 'WHITE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-006';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-006', '足取り軽め、轟はじめ 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇足取り軽め、轟はじめ 30", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-006', 'ありあとりゃあすっ 50+', '自分のステージに異なるカード名の#ReGLOSSを持つホロメンが3人以上いる時、このアーツ+20。', '{"WHITE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白◇ありあとりゃあすっ 50+", "rawEffect": "自分のステージに異なるカード名の#ReGLOSSを持つホロメンが3人以上いる時、このアーツ+20。"}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-007', '轟はじめ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-007_U.png', 'MEMBER', 'HSD05', 'HSD05-007', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=523&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-007', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-007_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=523&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-007', 120, 'FIRST', 'WHITE', NULL, 1, '{"キーワード": "ブルームエフェクト宇宙一の番長を目指すなんでも屋 \n自分のデッキを1枚引く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-007', '度胸、愛嬌、最強 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇度胸、愛嬌、最強 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-008', '轟はじめ', 'R', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-008_R.png', 'MEMBER', 'HSD05', 'HSD05-008', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=524&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-008', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-008_R.png', 'https://hololive-official-cardgame.com/cardlist/?id=524&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-008', 230, 'FIRST', 'WHITE', NULL, 1, '{"エクストラ": "このホロメンがダウンした時、自分のライフ-2"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-008';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-008', '……なんか、番長っぽくなってきたかも！ 50', 'このターンの間、自分のステージの#ReGLOSSを持つDebutホロメン1人のアーツ+40。', '{"WHITE": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白白……なんか、番長っぽくなってきたかも！ 50", "rawEffect": "このターンの間、自分のステージの#ReGLOSSを持つDebutホロメン1人のアーツ+40。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-009', '轟はじめ', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-009_RR.png', 'MEMBER', 'HSD05', 'HSD05-009', '["#DEV_IS", "#ReGLOSS", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=525&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-009', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-009_RR.png', 'https://hololive-official-cardgame.com/cardlist/?id=525&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-009', 180, 'SECOND', 'WHITE', NULL, 2, '{"キーワード": "ブルームエフェクトダンスでこの世界に彩を！ \n自分のデッキから、#ReGLOSSを持つ[Debutホロメンか1stホロメン]1枚を公開し、手札に加える。そしてデッキをシャッフルする。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-009', '滅紫の雷 80+紫+50', '自分のステージに〈轟はじめ〉以外の#ReGLOSSを持つホロメンがいる時、このアーツ+30。', '{"WHITE": 2, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白白◇滅紫の雷 80+紫+50", "rawEffect": "自分のステージに〈轟はじめ〉以外の#ReGLOSSを持つホロメンがいる時、このアーツ+30。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-010', '儒烏風亭らでん', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-010_U.png', 'MEMBER', 'HSD05', 'HSD05-010', '["#DEV_IS", "#ReGLOSS", "#お酒"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=526&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-010', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-010_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=526&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-010', 80, 'DEBUT', 'GREEN', NULL, 0, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-010';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-010', 'ちょいと一席 20', '自分のアーカイブのエール1枚を、自分の#ReGLOSSを持つホロメンに送れる。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇ちょいと一席 20", "rawEffect": "自分のアーカイブのエール1枚を、自分の#ReGLOSSを持つホロメンに送れる。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-011', '一条莉々華', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-011_U.png', 'MEMBER', 'HSD05', 'HSD05-011', '["#DEV_IS", "#ReGLOSS", "#料理"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=527&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-011', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-011_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=527&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-011', 70, 'DEBUT', 'RED', NULL, 0, '{"キーワード": "コラボエフェクト任せておきなさい！ \n自分のセンターホロメンが#ReGLOSSを持つ時、自分の手札が5枚以下なら、自分のデッキを1枚引く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-011';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-011', '社長の推し事 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇社長の推し事 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-012', '火威青', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-012_U.png', 'MEMBER', 'HSD05', 'HSD05-012', '["#DEV_IS", "#ReGLOSS", "#絵"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=528&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-012', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-012_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=528&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-012', 70, 'DEBUT', 'BLUE', NULL, 0, '{"キーワード": "コラボエフェクトドーンッ！ \n相手のセンターホロメンかバックホロメン1人に特殊ダメージ10を与える。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-012';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-012', '世界一かわいいよ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇世界一かわいいよ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD05-013', '音乃瀬奏', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-013_U.png', 'MEMBER', 'HSD05', 'HSD05-013', '["#DEV_IS", "#ReGLOSS", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=529&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD05-013', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD05/hSD05-013_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=529&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD05-013', 90, 'DEBUT', 'YELLOW', NULL, 0, '{"キーワード": "コラボエフェクトクレッシェンドな日々 \n自分のステージのエール1枚を、このホロメン以外の自分のホロメンに付け替えられる。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD05-013';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD05-013', 'ガハw 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇ガハw 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY01-001', '白エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY01-001_C.png', 'CHEER', 'HY01', 'HY01-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=168&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY01-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY01-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=168&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD05&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

COMMIT;
