-- 匯入官方卡表批次資料（來源：HSD06）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD06&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-011', 'ﾁｬｷ丸', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-011_C.png', 'SUPPORT', 'HSD06', 'HSD06-011', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=544&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-011', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-011_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=544&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-012', 'ぽこべぇ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-012_C.png', 'SUPPORT', 'HSD06', 'HSD06-012', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=545&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-012', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-012_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=545&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-048', '風真いろは', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hBP01-048_C_2.png', 'MEMBER', 'HBP01', 'HBP01-048', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=533&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-048', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hBP01-048_C_2.png', 'https://hololive-official-cardgame.com/cardlist/?id=533&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP01-048', 120, 'DEBUT', 'GREEN', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP01-048';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP01-048', '皆殿、風真いろはでござる～ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇皆殿、風真いろはでござる～ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-050', '風真いろは', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hBP01-050_U_2.png', 'MEMBER', 'HBP01', 'HBP01-050', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=538&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-050', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hBP01-050_U_2.png', 'https://hololive-official-cardgame.com/cardlist/?id=538&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP01-050', 140, 'FIRST', 'GREEN', NULL, 1, '{"キーワード": "ギフト用心棒 \n[コラボポジション限定]相手のホロメンのアーツは、自分のコラボホロメンしか対象にできない。ただし、特殊ダメージは除く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP01-050';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP01-050', '元気を全力でお届けします！ 20', '自分のエールデッキの上から1枚を、自分の〈風真いろは〉以外の#秘密結社holoXを持つホロメンに送る。', '{"GREEN": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "緑◇元気を全力でお届けします！ 20", "rawEffect": "自分のエールデッキの上から1枚を、自分の〈風真いろは〉以外の#秘密結社holoXを持つホロメンに送る。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-104', 'ふつうのパソコン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-104_C.png', 'SUPPORT', 'HBP01', 'HBP01-104', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=145&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-104', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-104_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=145&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP02-076', 'カスタムパソコン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP02/hBP02-076_C.png', 'SUPPORT', 'HBP02', 'HBP02-076', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=343&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP02-076', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP02/hBP02-076_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=343&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP02-080', '秘密結社holoX', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP02/hBP02-080_U.png', 'SUPPORT', 'HBP02', 'HBP02-080', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=347&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP02-080', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP02/hBP02-080_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=347&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-016', '春先のどか', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-016_C.png', 'SUPPORT', 'HSD01', 'HSD01-016', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=16&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-016', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-016_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=16&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-017', 'マネちゃん', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'SUPPORT', 'HSD01', 'HSD01-017', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-017', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-001', '風真いろは', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-001_OC.png', 'OSHI', 'HSD06', 'HSD06-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=532&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-001_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=532&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD06-001', 5, 'GREEN', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD06-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD06-001', 'NORMAL', 'グリーンマイク', '[ターンに1回]このターンの間、自分の緑センターホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]このターンの間、自分の緑センターホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD06-001', 'SP', 'みんな頑張ろー！', '[ゲームに1回]自分の緑ホロメン全員のHP20回復。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]自分の緑ホロメン全員のHP20回復。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-002', '風真いろは', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-002_C.png', 'MEMBER', 'HSD06', 'HSD06-002', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=534&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-002', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-002_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=534&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-002', 80, 'DEBUT', 'GREEN', NULL, 0, '{"キーワード": "コラボエフェクトのっと！ﾆﾝﾆﾝ！！ \n自分のホロメン1人のHP10回復。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-002';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-002', 'いえす！ｼﾞｬｷﾝｼﾞｬｷﾝ！！ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇いえす！ｼﾞｬｷﾝｼﾞｬｷﾝ！！ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-003', '風真いろは', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-003_U.png', 'MEMBER', 'HSD06', 'HSD06-003', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=535&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-003', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-003_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=535&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-003', 80, 'DEBUT', 'GREEN', NULL, 0, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-003', '一刀両断叩き斬る 30+', '自分のセンターホロメンのHPが減っている時、このアーツ+10。', '{"GREEN": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "緑一刀両断叩き斬る 30+", "rawEffect": "自分のセンターホロメンのHPが減っている時、このアーツ+10。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-004', '風真いろは', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-004_C.png', 'MEMBER', 'HSD06', 'HSD06-004', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=536&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-004', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-004_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=536&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-004', 160, 'FIRST', 'GREEN', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-004', '照れ屋な用心棒 60', '', '{"GREEN": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "緑◇照れ屋な用心棒 60", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-005', '風真いろは', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-005_C.png', 'MEMBER', 'HSD06', 'HSD06-005', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=537&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-005', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-005_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=537&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-005', 120, 'FIRST', 'GREEN', NULL, 1, '{"キーワード": "ブルームエフェクトかざまとおでかけ \n自分のエールデッキの上から1枚を、自分の#秘密結社holoXを持つホロメンに送る。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-005', 'かざまといっしょ！ 30', '', '{"GREEN": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "緑かざまといっしょ！ 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-006', '風真いろは', 'R', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-006_R.png', 'MEMBER', 'HSD06', 'HSD06-006', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=539&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-006', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-006_R.png', 'https://hololive-official-cardgame.com/cardlist/?id=539&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-006', 220, 'FIRST', 'GREEN', NULL, 1, '{"キーワード": "ブルームエフェクトサムライ少女 \n自分のデッキから、[〈ﾁｬｷ丸〉か〈ぽこべぇ〉]1枚を公開し、手札に加える。そしてデッキをシャッフルする。", "エクストラ": "このホロメンがダウンした時、自分のライフ-2"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-006';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-006', '刀の錆になるでござる！ 50', '', '{"GREEN": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "緑◇刀の錆になるでござる！ 50", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-007', '風真いろは', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-007_RR.png', 'MEMBER', 'HSD06', 'HSD06-007', '["#JP", "#秘密結社holoX"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=540&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-007', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-007_RR.png', 'https://hololive-official-cardgame.com/cardlist/?id=540&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-007', 180, 'SECOND', 'GREEN', NULL, 2, '{"キーワード": "ブルームエフェクト元気をお届け \n自分の#秘密結社holoXを持つホロメン1人のHP30回復。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-007', '天才では？ 70+青+50', '自分のステージにエールが5枚以上ある時、このアーツ+50。', '{"GREEN": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "緑◇◇天才では？ 70+青+50", "rawEffect": "自分のステージにエールが5枚以上ある時、このアーツ+50。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-008', '博衣こより', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-008_U.png', 'MEMBER', 'HSD06', 'HSD06-008', '["#JP", "#秘密結社holoX", "#ケモミミ"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=541&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-008', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-008_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=541&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-008', 70, 'DEBUT', 'WHITE', NULL, 0, '{"キーワード": "コラボエフェクトずのー！ \n自分のセンターホロメンが#秘密結社holoXを持つ時、自分の手札が5枚以下なら、自分のデッキを1枚引く。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-008';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-008', 'どやぁ 10', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇どやぁ 10", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-009', '鷹嶺ルイ', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-009_U.png', 'MEMBER', 'HSD06', 'HSD06-009', '["#JP", "#秘密結社holoX", "#トリ", "#お酒"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=542&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-009', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-009_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=542&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-009', 80, 'DEBUT', 'RED', NULL, 0, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-009', '頼れる女幹部 20', '自分のアーカイブの#秘密結社holoXを持つDebutホロメン1枚を手札に戻せる。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇頼れる女幹部 20", "rawEffect": "自分のアーカイブの#秘密結社holoXを持つDebutホロメン1枚を手札に戻せる。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD06-010', 'ラプラス・ダークネス', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-010_U.png', 'MEMBER', 'HSD06', 'HSD06-010', '["#JP", "#秘密結社holoX", "#シューター"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=543&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD06-010', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD06/hSD06-010_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=543&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD06-010', 60, 'DEBUT', 'PURPLE', NULL, 0, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD06-010';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD06-010', '狂気の宴 30+', '[コラボポジション限定]このターンの自分のメインステップに自分のSP推しスキルを使っていた時、このアーツ+50。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇狂気の宴 30+", "rawEffect": "[コラボポジション限定]このターンの自分のメインステップに自分のSP推しスキルを使っていた時、このアーツ+50。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY02-001', '緑エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY02-001_C.png', 'CHEER', 'HY02', 'HY02-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=169&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY02-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY02-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=169&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD06&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

COMMIT;
