-- 匯入官方卡表批次資料（來源：HSD08）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD08&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-009', '天音かなた', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hBP01-009_C.png', 'MEMBER', 'HBP01', 'HBP01-009', '["#JP", "#4期生", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=40&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-009', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hBP01-009_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=40&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP01-009', 90, 'DEBUT', 'WHITE', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP01-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP01-009', 'こんかなた～ 40', 'このアーツは、相手のセンターホロメンしか対象にできない。', '{"WHITE": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白こんかなた～ 40", "rawEffect": "このアーツは、相手のセンターホロメンしか対象にできない。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-011', '天音かなた', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-011_C.png', 'MEMBER', 'HBP01', 'HBP01-011', '["#JP", "#4期生", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=42&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-011', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-011_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=42&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP01-011', 150, 'FIRST', 'WHITE', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP01-011';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP01-011', '塩対応かなたそ 20', '', '{"WHITE": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白塩対応かなたそ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-013', '天音かなた', 'R', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hBP01-013_R_02.png', 'MEMBER', 'HBP01', 'HBP01-013', '["#JP", "#4期生", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=44&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-013', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hBP01-013_R_02.png', 'https://hololive-official-cardgame.com/cardlist/?id=44&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP01-013', 100, 'FIRST', 'WHITE', NULL, 1, '{"キーワード": "ブルームエフェクト天使のお仕事 \n相手のセンターホロメンに特殊ダメージ30を与える（ダウンしても相手のライフは減らない）。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP01-013';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP01-013', 'エンジェルステージ 50', '', '{"WHITE": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白◇エンジェルステージ 50", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-108', 'じゃあ敵だね', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-108_U.png', 'SUPPORT', 'HBP01', 'HBP01-108', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=149&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-108', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-108_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=149&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-116', 'うぱお', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-116_C.png', 'SUPPORT', 'HBP01', 'HBP01-116', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=157&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-116', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP01/hBP01-116_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=157&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP02-084', 'みっころね24', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP02/hBP02-084_U.png', 'SUPPORT', 'HBP02', 'HBP02-084', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=351&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP02-084', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hBP02/hBP02-084_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=351&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-017', 'マネちゃん', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'SUPPORT', 'HSD01', 'HSD01-017', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-017', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD01/hSD01-017_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=17&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-001', '天音かなた', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-001_OC.png', 'OSHI', 'HSD08', 'HSD08-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1138&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-001_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=1138&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD08-001', 5, 'WHITE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD08-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD08-001', 'NORMAL', 'ホワイトマイク', '[ターンに1回]このターンの間、自分の白センターホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]このターンの間、自分の白センターホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD08-001', 'SP', 'クイックガード', '[ゲームに1回]相手のターンで、自分の白ホロメンが相手からダメージを受ける時に使える：そのホロメン1人が受けるダメージ-20。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]相手のターンで、自分の白ホロメンが相手からダメージを受ける時に使える：そのホロメン1人が受けるダメージ-20。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-002', '天音かなた', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-002_U.png', 'MEMBER', 'HSD08', 'HSD08-002', '["#JP", "#4期生", "#歌", "#サマー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1139&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-002', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-002_U.png', 'https://hololive-official-cardgame.com/cardlist/?id=1139&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD08-002', 100, 'DEBUT', 'WHITE', NULL, 0, '{"キーワード": "コラボエフェクトホロサマー \n自分のデッキの上から5枚を見る。その中から、#サマーを持つDebutホロメン1枚を公開し、手札に加える。そして残ったカードを好きな順でデッキの下に戻す。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD08-002';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD08-002', '浴衣似合うでしょ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇浴衣似合うでしょ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-003', '天音かなた', 'R', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-003_R.png', 'MEMBER', 'HSD08', 'HSD08-003', '["#JP", "#4期生", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1140&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-003', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-003_R.png', 'https://hololive-official-cardgame.com/cardlist/?id=1140&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD08-003', 200, 'SECOND', 'WHITE', NULL, 2, '{"キーワード": "ブルームエフェクト相談のるよ \n自分のデッキから、#4期生を持つDebutホロメン1枚を公開し、手札に加える。そしてデッキをシャッフルする。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD08-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD08-003', 'みんなのスパダリ 100+緑+50', '自分のステージの#サマーを持つホロメン1人につき、このアーツ+10。', '{"WHITE": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白◇◇みんなのスパダリ 100+緑+50", "rawEffect": "自分のステージの#サマーを持つホロメン1人につき、このアーツ+10。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-004', '天音かなた', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-004_RR.png', 'MEMBER', 'HSD08', 'HSD08-004', '["#JP", "#4期生", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1141&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-004', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-004_RR.png', 'https://hololive-official-cardgame.com/cardlist/?id=1141&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD08-004', 180, 'SECOND', 'WHITE', NULL, 2, '{"キーワード": "ギフトエンジェルウィンド \n[センターポジション限定]自分のコラボポジションの#4期生を持つDebutホロメンのアーツ+40。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD08-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD08-004', 'きみの背中に追いつけるように 120赤+50', '[ターンに1回]このアーツで相手のセンターホロメンをダウンさせた時、相手の2ndホロメン1人に特殊ダメージ40を与える。', '{"WHITE": 2, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白白◇きみの背中に追いつけるように 120赤+50", "rawEffect": "[ターンに1回]このアーツで相手のセンターホロメンをダウンさせた時、相手の2ndホロメン1人に特殊ダメージ40を与える。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-005', '姫森ルーナ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-005_C.png', 'MEMBER', 'HSD08', 'HSD08-005', '["#JP", "#4期生", "#ベイビー", "#サマー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1142&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-005', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-005_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=1142&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD08-005', 90, 'DEBUT', 'WHITE', NULL, 0, '{"キーワード": "ギフトなんでも入る巾着 \n[コラボポジション限定]相手のターンで、自分のホロメンがダウンした時、自分のライフが相手以下なら、自分のアーカイブのカード名に「パソコン」を含むアイテム1枚を手札に戻せる。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD08-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD08-005', 'お祭りなのら 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇お祭りなのら 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-006', '常闇トワ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-006_C.png', 'MEMBER', 'HSD08', 'HSD08-006', '["#JP", "#4期生", "#歌", "#シューター", "#サマー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1143&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-006', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-006_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=1143&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD08-006', 90, 'DEBUT', 'PURPLE', NULL, 0, '{"キーワード": "コラボエフェクト花火見ていく？ \n相手のセンターホロメンに特殊ダメージ10を与える。自分が後攻で最初のターンなら、かわりに、相手のセンターホロメンに特殊ダメージ20を与える。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD08-006';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD08-006', 'トワに見惚れちゃった？ 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇トワに見惚れちゃった？ 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD08-007', '角巻わため', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-007_C.png', 'MEMBER', 'HSD08', 'HSD08-007', '["#JP", "#4期生", "#ケモミミ", "#歌", "#サマー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1144&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD08-007', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD08-007_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=1144&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD08-007', 100, 'DEBUT', 'YELLOW', NULL, 0, '{"キーワード": "コラボエフェクトみんなと夏祭り \n自分のアーカイブのエール1枚を自分の#4期生を持つ2ndホロメンに送れる。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD08-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD08-007', 'わたあめおいしいねぇ 10', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇わたあめおいしいねぇ 10", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY01-001', '白エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY01-001_C.png', 'CHEER', 'HY01', 'HY01-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=168&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY01-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY01-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=168&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP03-093', 'ホロライブ4期生', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hBP03-093_U_02.png', 'SUPPORT', 'HBP03', 'HBP03-093', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1146&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP03-093', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hBP03-093_U_02.png', 'https://hololive-official-cardgame.com/cardlist/?id=1146&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-016', '春先のどか', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD01-016_02_C.png', 'SUPPORT', 'HSD01', 'HSD01-016', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1145&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD08&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-016', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD08/hSD01-016_02_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=1145&%2Fcardlist%2Fcardsearch_ex=&expansion=hSD08&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

COMMIT;
