-- 匯入官方卡表批次資料（來源：HCS01）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hCS01&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-081', '星街すいせい', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP01-081_02_SR.png', 'MEMBER', 'HBP01', 'HBP01-081', '["#JP", "#0期生", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1174&expansion=hCS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-081', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP01-081_02_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=1174&expansion=hCS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP01-081', 210, 'SECOND', 'BLUE', NULL, 2, '{"キーワード": "コラボエフェクト空を駆ける光 \n自分のエールデッキの上から1枚を、自分の青ホロメンに送る。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP01-081';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP01-081', '輝く彗星 60+赤+50', 'このホロメンの青エール2枚をアーカイブできる：このホロメンに重なっているホロメン1枚につき、このアーツ+60（このアーツは相手のバックホロメンも対象にできる）。', '{"BLUE": 3, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "青青青◇輝く彗星 60+赤+50", "rawEffect": "このホロメンの青エール2枚をアーカイブできる：このホロメンに重なっているホロメン1枚につき、このアーツ+60（このアーツは相手のバックホロメンも対象にできる）。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP02-013', '白上フブキ', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP02-013_02_SR.png', 'MEMBER', 'HBP02', 'HBP02-013', '["#JP", "#1期生", "#ゲーマーズ", "#ケモミミ", "#絵"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1175&expansion=hCS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP02-013', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP02-013_02_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=1175&expansion=hCS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP02-013', 180, 'SECOND', 'WHITE', NULL, 2, '{"キーワード": "ギフトみんなと一緒！ \nこのホロメンは、異なるカード名のマスコットを2枚まで付けられる。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP02-013';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP02-013', 'マスコットたちの饗宴 80+紫+50', '自分のステージのマスコット1枚につき、このアーツ+20。', '{"WHITE": 2, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白白◇マスコットたちの饗宴 80+紫+50", "rawEffect": "自分のステージのマスコット1枚につき、このアーツ+20。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP03-030', 'さくらみこ', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP03-030_02_SR.png', 'MEMBER', 'HBP03', 'HBP03-030', '["#JP", "#0期生", "#ベイビー"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1176&expansion=hCS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP03-030', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP03-030_02_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=1176&expansion=hCS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP03-030', 200, 'SECOND', 'RED', NULL, 2, '{"キーワード": "ギフトエリートギャンブル \n[センターポジション限定][ターンに1回]自分のメインステップで、このホロメンに〈35P〉が付いている時、サイコロを1回振れる：3か5の時、このターンの間、このホロメンのアーツ+50。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP03-030';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP03-030', 'エリート巫女 120+緑+50', 'このホロメンに付いている〈35P〉1枚につき、このアーツ+20。', '{"RED": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "赤◇◇エリート巫女 120+緑+50", "rawEffect": "このホロメンに付いている〈35P〉1枚につき、このアーツ+20。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP04-013', '博衣こより', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP04-013_02_SR.png', 'MEMBER', 'HBP04', 'HBP04-013', '["#JP", "#秘密結社holoX", "#ケモミミ"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1177&expansion=hCS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP04-013', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP04-013_02_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=1177&expansion=hCS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP04-013', 200, 'SECOND', 'WHITE', NULL, 2, '{"キーワード": "ギフト絶対諦めない！ \nこのホロメンが相手のホロメンをダウンさせた時、自分のデッキの上から1枚をホロパワーにする。その後、自分のホロパワーを見る。その中から1枚を公開し、手札に加える。そしてホロパワーをシャッフルする。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP04-013';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP04-013', 'かくせいのこより 160緑+50', 'このホロメンに#こよラボを持つサポートカードが付いている時、自分のデッキから、#こよラボを持つサポートカード1枚を公開し、手札に加える。そしてデッキをシャッフルする。', '{"WHITE": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "白◇◇かくせいのこより 160緑+50", "rawEffect": "このホロメンに#こよラボを持つサポートカードが付いている時、自分のデッキから、#こよラボを持つサポートカード1枚を公開し、手札に加える。そしてデッキをシャッフルする。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP04-059', 'ラプラス・ダークネス', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP04-059_02_SR.png', 'MEMBER', 'HBP04', 'HBP04-059', '["#JP", "#秘密結社holoX", "#シューター"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1178&expansion=hCS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP04-059', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hCS01/hBP04-059_02_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=1178&expansion=hCS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HBP04-059', 200, 'SECOND', 'PURPLE', NULL, 2, '{"キーワード": "ブルームエフェクトYes My Dark！ \n自分の手札1枚をアーカイブすることで、サイコロを3回振れる：奇数が出た回数1回につき、自分のデッキを1枚引く。自分のブルームエフェクト「Yes My Dark！」はターンに1回しか使えない。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HBP04-059';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HBP04-059', '吾輩最強伝説 120青+50', '相手のセンターホロメンに、このターンに自分が能力でサイコロを振った回数1回につき、特殊ダメージ10を与える。', '{"PURPLE": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "紫◇◇吾輩最強伝説 120青+50", "rawEffect": "相手のセンターホロメンに、このターンに自分が能力でサイコロを振った回数1回につき、特殊ダメージ10を与える。"}'::jsonb, 0);

COMMIT;
