-- 匯入官方卡表批次資料（來源：HPC01）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hPC01&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP01-104', 'ふつうのパソコン', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hBP01-104_SR.png', 'SUPPORT', 'HBP01', 'HBP01-104', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=841&expansion=hPC01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP01-104', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hBP01-104_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=841&expansion=hPC01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP02-076', 'カスタムパソコン', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hBP02-076_SR.png', 'SUPPORT', 'HBP02', 'HBP02-076', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=844&expansion=hPC01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP02-076', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hBP02-076_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=844&expansion=hPC01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HBP02-077', 'レトロパソコン', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hBP02-077_SR.png', 'SUPPORT', 'HBP02', 'HBP02-077', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=845&expansion=hPC01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HBP02-077', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hBP02-077_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=845&expansion=hPC01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-018', 'サブパソコン', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hSD01-018_SR.png', 'SUPPORT', 'HSD01', 'HSD01-018', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=842&expansion=hPC01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-018', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hSD01-018_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=842&expansion=hPC01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD01-019', 'スゴイパソコン', 'SR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hSD01-019_SR.png', 'SUPPORT', 'HSD01', 'HSD01-019', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=843&expansion=hPC01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HSD01-019', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hPR/hSD01-019_SR.png', 'https://hololive-official-cardgame.com/cardlist/?id=843&expansion=hPC01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

COMMIT;
