-- 匯入官方卡表批次資料（來源：HYS01）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hYS01&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HYS01-001', '七詩ムメイ', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-001_OC.png', 'OSHI', 'HYS01', 'HYS01-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=172&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HYS01-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-001_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=172&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HYS01-001', 5, 'WHITE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HYS01-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-001', 'NORMAL', 'ホワイトバトン', '[ホロパワー：2消費][ターンに１回]このターンの間、自分の白コラボホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：2消費][ターンに１回]このターンの間、自分の白コラボホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-001', 'SP', 'クイックガード', '[ホロパワー：1消費][ゲームに１回]相手のターンで、自分の白ホロメンが相手からダメージを受ける時に使える：そのホロメン１人が受けるダメージ-20。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：1消費][ゲームに１回]相手のターンで、自分の白ホロメンが相手からダメージを受ける時に使える：そのホロメン１人が受けるダメージ-20。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HYS01-002', '兎田ぺこら', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-002_OC.png', 'OSHI', 'HYS01', 'HYS01-002', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=173&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HYS01-002', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-002_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=173&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HYS01-002', 5, 'GREEN', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HYS01-002';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-002', 'NORMAL', 'グリーンバトン', '[ホロパワー：2消費][ターンに１回]このターンの間、自分の緑コラボホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：2消費][ターンに１回]このターンの間、自分の緑コラボホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-002', 'SP', 'みんな頑張ろー！', '[ホロパワー：1消費][ゲームに１回]自分の緑ホロメン全員のHP20回復。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：1消費][ゲームに１回]自分の緑ホロメン全員のHP20回復。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HYS01-003', '小鳥遊キアラ', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-003_OC.png', 'OSHI', 'HYS01', 'HYS01-003', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=174&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HYS01-003', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-003_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=174&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HYS01-003', 5, 'RED', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HYS01-003';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-003', 'NORMAL', 'レッドバトン', '[ホロパワー：2消費][ターンに１回]このターンの間、自分の赤コラボホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：2消費][ターンに１回]このターンの間、自分の赤コラボホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-003', 'SP', 'さあ！もう一度！', '[ホロパワー：1消費][ゲームに１回]自分のアーカイブの赤ホロメン１枚を手札に戻す。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：1消費][ゲームに１回]自分のアーカイブの赤ホロメン１枚を手札に戻す。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HYS01-004', '星街すいせい', 'OC', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-004_OC.png', 'OSHI', 'HYS01', 'HYS01-004', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=175&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HYS01-004', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hY01/hYS01-004_OC.png', 'https://hololive-official-cardgame.com/cardlist/?id=175&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HYS01-004', 5, 'BLUE', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HYS01-004';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-004', 'NORMAL', 'ブルーバトン', '[ホロパワー：2消費][ターンに１回]このターンの間、自分の青コラボホロメンのアーツ+20。', 2, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：2消費][ターンに１回]このターンの間、自分の青コラボホロメンのアーツ+20。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HYS01-004', 'SP', 'バックショット', '[ホロパワー：1消費][ゲームに１回]自分のホロメンが相手のバックホロメンにダメージを与えた時に使える：その相手のバックホロメン１人に特殊ダメージ50を与える。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ホロパワー：1消費][ゲームに１回]自分のホロメンが相手のバックホロメンにダメージを与えた時に使える：その相手のバックホロメン１人に特殊ダメージ50を与える。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY01-001', '白エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY01-001_C.png', 'CHEER', 'HY01', 'HY01-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=168&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY01-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY01-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=168&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY02-001', '緑エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY02-001_C.png', 'CHEER', 'HY02', 'HY02-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=169&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY02-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY02-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=169&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY03-001', '赤エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY03-001_C.png', 'CHEER', 'HY03', 'HY03-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=170&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY03-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY03-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=170&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HY04-001', '青エール', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY04-001_C.png', 'CHEER', 'HY04', 'HY04-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=171&expansion=hYS01&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO card_variants (card_id, variant_code, variant_name, image_url, source_url, is_default) VALUES ('HY04-001', 'DEFAULT', '預設圖', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/COMMON/hY04-001_C.png', 'https://hololive-official-cardgame.com/cardlist/?id=171&expansion=hYS01&view=text', TRUE) ON CONFLICT (card_id, variant_code) DO UPDATE SET variant_name = EXCLUDED.variant_name, image_url = EXCLUDED.image_url, source_url = EXCLUDED.source_url, is_default = EXCLUDED.is_default, updated_at = CURRENT_TIMESTAMP;

COMMIT;
