-- 匯入官方卡表批次資料（來源：HSD13）
-- 由 scripts/official_card_import.py 產生，請勿手動大幅改寫。
-- Source: https://hololive-official-cardgame.com/cardlist/cardsearch/?expansion=hSD13&view=text&sort=new

BEGIN;

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-001', 'エリザベス・ローズ・ブラッドフレイム', 'OSR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-001_OSR.png', 'OSHI', 'HSD13', 'HSD13-001', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1769&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD13-001', 5, 'RED', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD13-001';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD13-001', 'NORMAL', '秩序の先駆者', '[ターンに1回]自分のホロメン1人が相手からアーツダメージを受ける時、自分のステージの[Buzzか2nd]の赤ホロメン1人を選べる：そのダメージを、選んだホロメンがかわりに受ける。', 3, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]自分のホロメン1人が相手からアーツダメージを受ける時、自分のステージの[Buzzか2nd]の赤ホロメン1人を選べる：そのダメージを、選んだホロメンがかわりに受ける。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD13-001', 'SP', 'JUST LIKE THAT', '[ゲームに1回]自分のアーカイブの#Justiceを持つホロメン1枚をステージに出す。その後、自分のアーカイブのエール1～5枚をそのホロメンに送る。', 3, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]自分のアーカイブの#Justiceを持つホロメン1枚をステージに出す。その後、自分のアーカイブのエール1～5枚をそのホロメンに送る。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-002', 'ジジ・ムリン', 'OSR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-002_OSR.png', 'OSHI', 'HSD13', 'HSD13-002', '[]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1770&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO oshi_cards (card_id, life, main_color, sub_color) VALUES ('HSD13-002', 5, 'YELLOW', NULL) ON CONFLICT (card_id) DO UPDATE SET life = EXCLUDED.life, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, updated_at = CURRENT_TIMESTAMP;
DELETE FROM oshi_skills WHERE oshi_card_id = 'HSD13-002';
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD13-002', 'NORMAL', 'Boat Goes Binted', '[ターンに1回]相手のセンターポジションとコラボポジションのホロメンを入れ替える。', 1, '{"type": "UNIMPLEMENTED", "rawText": "[ターンに1回]相手のセンターポジションとコラボポジションのホロメンを入れ替える。"}'::jsonb);
INSERT INTO oshi_skills (oshi_card_id, skill_type, skill_name, description, holopower_cost, effect_json) VALUES ('HSD13-002', 'SP', '自由奔放な『追跡者』', '[ゲームに1回]自分のデッキから、2ndホロメンの〈ジジ・ムリン〉2枚を公開し、ステージに出す。そしてデッキをシャッフルする。その後、自分のアーカイブのエールを自分のホロメン全員に1枚ずつ送る。', 3, '{"type": "UNIMPLEMENTED", "rawText": "[ゲームに1回]自分のデッキから、2ndホロメンの〈ジジ・ムリン〉2枚を公開し、ステージに出す。そしてデッキをシャッフルする。その後、自分のアーカイブのエールを自分のホロメン全員に1枚ずつ送る。"}'::jsonb);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-003', 'エリザベス・ローズ・ブラッドフレイム', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-003_C.png', 'MEMBER', 'HSD13', 'HSD13-003', '["#EN", "#Justice", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1771&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-003', 140, 'DEBUT', 'RED', NULL, 0, '{"エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-003';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-003', 'オーッホッホッホッ！ 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇オーッホッホッホッ！ 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-004', 'エリザベス・ローズ・ブラッドフレイム', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-004_C.png', 'MEMBER', 'HSD13', 'HSD13-004', '["#EN", "#Justice", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1772&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-004', 170, 'FIRST', 'RED', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-004';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-004', '薔薇は赤い 40', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇薔薇は赤い 40", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-004', '私の心の炎は青い 140', '', '{"RED": 1, "COLORLESS": 3}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "赤◇◇◇私の心の炎は青い 140", "rawEffect": ""}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-005', 'エリザベス・ローズ・ブラッドフレイム', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-005_U.png', 'MEMBER', 'HSD13', 'HSD13-005', '["#EN", "#Justice", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1773&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-005', 160, 'FIRST', 'RED', NULL, 1, '{"キーワード": "ギフトFor Justice! -ERB- \n相手のターンで、自分の#Justiceを持つホロメンがダウンした時、自分のエールデッキの上から1枚をこのホロメンに送る。自分のギフト「For Justice! -ERB-」はターンに1回しか使えない。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-005';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-005', 'Lovely to See You, to See You, Lovely～♡ 50', '', '{"RED": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "赤◇Lovely to See You, to See You, Lovely～♡ 50", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-006', 'エリザベス・ローズ・ブラッドフレイム', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-006_U.png', 'MEMBER', 'HSD13', 'HSD13-006', '["#EN", "#Justice", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1774&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-006', 150, 'FIRST', 'RED', NULL, 1, '{"キーワード": "ブルームエフェクトBring It On! \n自分のステージの#Justiceを持つホロメン1人を選ぶ。このターンの間、選んだホロメンのアーツ+20。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-006';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-006', '守護るべきもの 30', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇守護るべきもの 30", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-007', 'エリザベス・ローズ・ブラッドフレイム', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-007_RR.png', 'MEMBER', 'HSD13', 'HSD13-007', '["#EN", "#Justice", "#歌"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1775&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-007', 180, 'SECOND', 'RED', NULL, 2, '{"キーワード": "ギフト猛炎のウォークライ \nこのホロメンのエール1枚につき、このホロメンのHP+10。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-007';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-007', '悪斬りのカデンツァ 100+紫+50', 'このホロメンのエール1枚につき、このアーツ+20。このアーツで相手のホロメンをダウンさせた時、自分のエールデッキの上から1枚をこのホロメンに送る。', '{"RED": 1, "COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "赤◇◇悪斬りのカデンツァ 100+紫+50", "rawEffect": "このホロメンのエール1枚につき、このアーツ+20。このアーツで相手のホロメンをダウンさせた時、自分のエールデッキの上から1枚をこのホロメンに送る。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-008', 'ジジ・ムリン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-008_C.png', 'MEMBER', 'HSD13', 'HSD13-008', '["#EN", "#Justice"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1776&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-008', 100, 'DEBUT', 'YELLOW', NULL, 0, '{"キーワード": "コラボエフェクトFor Justice! -GG- \n自分のアーカイブのエール1枚を自分の#Justiceを持つホロメンに送る。", "エクストラ": "このホロメンはデッキに何枚でも入れられる"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-008';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-008', 'GI MURIN!!!! 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇GI MURIN!!!! 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-009', 'ジジ・ムリン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-009_C.png', 'MEMBER', 'HSD13', 'HSD13-009', '["#EN", "#Justice"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1777&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-009', 120, 'DEBUT', 'YELLOW', NULL, 0, '{"キーワード": "コラボエフェクトイタズラ増殖！ \n自分が後攻で最初のターンなら、自分のデッキから、#Justiceを持つ1stホロメン1枚を公開し、ステージに出す。そしてデッキをシャッフルする。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-009';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-009', 'YIPPEEE 20', '', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇YIPPEEE 20", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-010', 'ジジ・ムリン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-010_C.png', 'MEMBER', 'HSD13', 'HSD13-010', '["#EN", "#Justice"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1778&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-010', 180, 'FIRST', 'YELLOW', NULL, 1, NULL, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-010';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-010', '周囲の頭痛の種 40', '', '{"YELLOW": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄周囲の頭痛の種 40", "rawEffect": ""}'::jsonb, 0);
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-010', '悪戯好きのグレムリン 60', '', '{"YELLOW": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄◇悪戯好きのグレムリン 60", "rawEffect": ""}'::jsonb, 1);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-011', 'ジジ・ムリン', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-011_U.png', 'MEMBER', 'HSD13', 'HSD13-011', '["#EN", "#Justice"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1779&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-011', 140, 'FIRST', 'YELLOW', NULL, 1, '{"キーワード": "ブルームエフェクトI am Gonathan G. \nこのホロメンに重なっているDebutホロメン1枚をアーカイブできる：相手のコラボホロメンに特殊ダメージ20を与える。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-011';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-011', 'すべての意味を追い求めて 40+', 'このホロメンに重なっているホロメンが0枚なら、このアーツ+20。', '{"YELLOW": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄◇すべての意味を追い求めて 40+", "rawEffect": "このホロメンに重なっているホロメンが0枚なら、このアーツ+20。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-012', 'ジジ・ムリン', 'U', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-012_U.png', 'MEMBER', 'HSD13', 'HSD13-012', '["#EN", "#Justice"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1780&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-012', 170, 'FIRST', 'YELLOW', NULL, 1, '{"キーワード": "ギフトご苦労さん！ \n相手のターンで、自分のバックホロメンが相手から特殊ダメージを受ける時、このホロメンに重なっているホロメン1枚をアーカイブできる：このターンの間、自分のバックホロメン全員は特殊ダメージを受けない。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-012';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-012', '負けるわけにはいかない 60', '', '{"YELLOW": 1, "COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄◇負けるわけにはいかない 60", "rawEffect": ""}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-013', 'ジジ・ムリン', 'RR', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-013_RR.png', 'MEMBER', 'HSD13', 'HSD13-013', '["#EN", "#Justice"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1781&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-013', 210, 'SECOND', 'YELLOW', NULL, 2, '{"キーワード": "ギフト再起のストレングス \n[ターンに1回]自分のメインステップで、自分の〈ジジ・ムリン〉に重なっているホロメン1枚をアーカイブできる：自分のエールデッキの上から1枚をこのホロメンに送る。"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-013';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-013', '殻破りのライオット 90+白+50', 'このホロメンに重なっているホロメンが0枚なら、このアーツ+90。', '{"YELLOW": 1, "COLORLESS": 3}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "黄◇◇◇殻破りのライオット 90+白+50", "rawEffect": "このホロメンに重なっているホロメンが0枚なら、このアーツ+90。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-014', 'セシリア・イマーグリーン', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-014_C.png', 'MEMBER', 'HSD13', 'HSD13-014', '["#EN", "#Justice", "#語学"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1782&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-014', 160, 'SPOT', 'COLORLESS', NULL, 0, '{"キーワード": "ギフト正義の旋律 \n[センターポジション・コラボポジション限定][ターンに1回]自分の#Justiceを持つ[DebutホロメンかSpotホロメン]がステージに出た時、自分のデッキを1枚引く。", "エクストラ": "このホロメンはBloomできない"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-014';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-014', '紅茶をどうぞ！ 40', '自分のエールデッキの上から1枚を自分の#Justiceを持つホロメンに送る。', '{"COLORLESS": 2}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇◇紅茶をどうぞ！ 40", "rawEffect": "自分のエールデッキの上から1枚を自分の#Justiceを持つホロメンに送る。"}'::jsonb, 0);

INSERT INTO cards (card_id, name, rarity, image_url, card_type, expansion_code, card_no, tags_json, source_url) VALUES ('HSD13-015', 'ラオーラ・パンテーラ', 'C', 'https://hololive-official-cardgame.com/wp-content/images/cardlist/hSD13/hSD13-015_C.png', 'MEMBER', 'HSD13', 'HSD13-015', '["#EN", "#Justice", "#ケモミミ", "#絵"]'::jsonb, 'https://hololive-official-cardgame.com/cardlist/?id=1783&expansion=hSD13&view=text') ON CONFLICT (card_id) DO UPDATE SET name = EXCLUDED.name, rarity = EXCLUDED.rarity, image_url = EXCLUDED.image_url, card_type = EXCLUDED.card_type, expansion_code = EXCLUDED.expansion_code, card_no = EXCLUDED.card_no, tags_json = EXCLUDED.tags_json, source_url = EXCLUDED.source_url, updated_at = CURRENT_TIMESTAMP;
INSERT INTO member_cards (card_id, hp, level_type, main_color, sub_color, bloom_level, passive_effect_json, trigger_condition) VALUES ('HSD13-015', 160, 'SPOT', 'COLORLESS', NULL, 0, '{"キーワード": "コラボエフェクト正義の諧調 \n自分のステージのエール1枚をエールデッキの下に戻せる。戻したなら、自分のエールデッキから、エール1枚を公開し、自分のホロメンに送る。そしてエールデッキをシャッフルする。", "エクストラ": "このホロメンはBloomできない"}'::jsonb, NULL) ON CONFLICT (card_id) DO UPDATE SET hp = EXCLUDED.hp, level_type = EXCLUDED.level_type, main_color = EXCLUDED.main_color, sub_color = EXCLUDED.sub_color, bloom_level = EXCLUDED.bloom_level, passive_effect_json = EXCLUDED.passive_effect_json, trigger_condition = EXCLUDED.trigger_condition, updated_at = CURRENT_TIMESTAMP;
DELETE FROM member_arts WHERE member_card_id = 'HSD13-015';
INSERT INTO member_arts (member_card_id, name, description, cost_cheer_json, effect_json, order_index) VALUES ('HSD13-015', 'コーヒーをどうぞ！ 30+', '自分の#Justiceを持つ[センターホロメンとコラボホロメン]に異なる色のエールが付いているなら、このアーツ+20。', '{"COLORLESS": 1}'::jsonb, '{"type": "UNIMPLEMENTED", "rawHeader": "◇コーヒーをどうぞ！ 30+", "rawEffect": "自分の#Justiceを持つ[センターホロメンとコラボホロメン]に異なる色のエールが付いているなら、このアーツ+20。"}'::jsonb, 0);

COMMIT;
